### ISSUE TITLE
Doesn't work on small breakpoint

### ISSUE THREAD

**Issue by mats68** [AlexandreBonaventure/vue-mq#1]
Hello
I have following config:
`Vue.use(VueMq, {
  breakpoints: {
    xs: 400,
    lg: 1000,
    xl: 1400
  }
})`

in Template
`This: {{$mq}}`

It never shows the xs breakpoint. (lg and xl work)

I tested with chrome devtools

**Comment by AlexandreBonaventure** [comment]
@mats68 Are you sure your window can go smaller than 400px ?

**Comment by AlexandreBonaventure** [comment]
In the example url https://alexandrebonaventure.github.io/vue-mq/examples/
small breakpoint is working

**Comment by mats68** [comment]
Thanks, it works now after I added viewport meta tag (I used vue webpack-simple, maybe should be mentioned in docs)

**Comment by AlexandreBonaventure** [comment]
Ok, no problems. Cheers
