### ISSUE TITLE
How to add mutliple breakpoints in one check

### ISSUE THREAD

**Issue by stahlsparre** [AlexandreBonaventure/vue-mq#13]
Is this possible in a terse way? E.g. I'm a beginner mind you.

v-if="$mq === 'large' || 'medium'"

I'm currently using this which feels like a mouthfull.

v-if="$mq === 'smaller' || $mq === 'small'"

**Comment by AlexandreBonaventure** [comment]
Hi, 
I just merged (#11) which adress directly your question.
You can use Array syntax now in component, so:
`:mq="['small', 'smaller']"`
