### ISSUE TITLE
Not working with Nuxt

### ISSUE THREAD

**Issue by JanuszOsica** [AlexandreBonaventure/vue-mq#20]
Not working with Nuxt. ReferenceError "window is not defined"

**Comment by omm2** [comment]
Include this plugin only for client-side.
nuxt.config.js:
`{ src: '~/plugins/mq.js', ssr: false }`

plugins/mq.js:
`
import Vue from 'vue'
import VueMq from 'vue-mq'

Vue.use(VueMq, {
  breakpoints: {
    mobile: 690,
    tablet: 1023,
    desktop: Infinity
  }
})
`

**Comment by AlexandreBonaventure** [comment]
SSR support as of v1.0.0
