### ISSUE TITLE
MQ not available on initial load

### ISSUE THREAD

**Issue by TimRensen** [AlexandreBonaventure/vue-mq#23]
```
[Vue warn]: Property or method "$mq" is not defined on the instance but referenced during render. 

Make sure that this property is reactive, either in the data option, or for class-based components, 
by initializing the property. 
See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <App> at src/App.vue
       <Root>
```

I get this error message everytime I initial load my page. It doesnt work in developing mode with HMR active. After changing and saving the file without reloading the page but using HMR to update it the mediaquery seems to work. 
Same problem after building the project and uploading it to a webserver.

Do i miss something or is there a problem while using
node v8.12.0
vue v3.0.4
in my project?

My template:
```
<template>
    <div id="app">
        <div id="nav">
            <div>currentBreakpoint: {{$mq}}</div>
        </div>
    </div>
</template>
```

**Comment by mystrdat** [comment]
Same in `2.5.17`.

**Comment by MarcoGomesr** [comment]
if you use computed you wont see the error but  $mq is undefined after you reload the page


```
{{ device }}

....
computed: {
  device() {
    return this.$mq
  }
},
```

I tried saving the value but I'm getting the same error

**Comment by MarcoGomesr** [comment]
it works for me now that I moved my Vue instance to the bottom,

```
Vue.use(VueMq, {
	breakpoints: { 
	  mobile: 450,
	  tablet: 900,
	  laptop: 1250,
	  desktop: Infinity,
	}
  })

  /* eslint-disable no-new */
new Vue({
	el: '#app',
	router,
	components: { App },
	template: '<App/>'
  })
```
