### ISSUE TITLE
TypeError: window.matchMedia is not a function

### ISSUE THREAD

**Issue by LeCoupa** [AlexandreBonaventure/vue-mq#61]
I have this issue on Sentry and it seems to be related to `vue-mq`. Do you have any idea where it is coming from?

I am using `"nuxt-mq": "2.0.1"`.

<img width="1123" alt="Screenshot 2020-09-24 at 19 35 08" src="https://user-images.githubusercontent.com/1658644/94179691-25758200-fe9d-11ea-88d0-91f163ba4b1f.png">

**Comment by bobvandevijver** [comment]
Did you check the browser support note (https://github.com/AlexandreBonaventure/vue-mq#browser-support)?

**Comment by LeCoupa** [comment]
Sorry about that. Thank you @bobvandevijver!
