### ISSUE TITLE
Uncaught SyntaxError: missing } after property list

### ISSUE THREAD

**Issue by tomasts248** [AlexandreBonaventure/vue-mq#64]
I apologize I'm new to Vue.js so most likelty I'm doing  a mistake.
Took the code from the readme and changed custom values for , but it trows this error.
Current code, at which the error points
```
Vue.use(VueMq, {
  breakpoints: { // default breakpoints - customize this
    md: 767,
    lg: 1200,
    xl: Infinity,
  }
  defaultBreakpoint: 'md' // customize this for SSR
})


new Vue({
            el: '#sliderportafolio',
             data: {
              slides: 5
            },
            components: {
              'carousel-3d': window['carousel-3d'].Carousel3d,
              'slide': window['carousel-3d'].Slide
            },
            methods: {
             testClick: function (){
             //
             }
           }
          });
```

**Comment by craigrileyuk** [comment]
@tomasts248 - You're missing a comma before your 'defaultBreakpoint' property. It should be:

    Vue.use(VueMq, {
        breakpoints: { // default breakpoints - customize this
          md: 767,
          lg: 1200,
          xl: Infinity,
        },
        defaultBreakpoint: 'md' // customize this for SSR
      })

**Comment by tomasts248** [comment]
Thank you so much! :)
