### ISSUE TITLE
Is bili a needed dependency?

### ISSUE THREAD

**Issue by marcushultman** [AlexandreBonaventure/vue-mq#8]
It's huge, is it needed for other than packaging? I don't want to pull down so many babel & rollup dependencies. Was it meant to be put as `dev-dependency`?

**Comment by marcushultman** [comment]
@AlexandreBonaventure

**Comment by AlexandreBonaventure** [comment]
Yeah of course it was! Thanks

**Comment by marcushultman** [comment]
Great package otherwise! Really helpful, thanks!
